name: Daily Trading

on:
  schedule:
    # Run Monday to Friday at 9:20 AM IST (3:50 AM UTC)
    - cron: '50 3 * * 1-5'
  
  workflow_dispatch:  # Allow manual trigger

jobs:
  trading:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          pip install upstox-python-sdk numpy pandas scipy
      
      - name: Create token file
        run: |
          echo "${{ secrets.UPSTOX_ACCESS_TOKEN }}" > token.txt
      
      - name: Create logs directory
        run: |
          mkdir -p logs
      
      - name: Run trading
        run: |
          python main.py
        timeout-minutes: 390  # 6.5 hours (market hours)
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trading-logs-${{ github.run_number }}
          path: logs/
          retention-days: 30
      
      - name: Display final status
        if: always()
        run: |
          echo "Trading session completed"
          if [ -f logs/trading_*.log ]; then
            echo "Log file found - displaying last 50 lines:"
            tail -50 logs/trading_*.log
          else
            echo "No log file found"
          fi